version: '3'
services:
  app:
    build: .
    volumes:
      - ./db:/app/db
      - ./files:/app/files
    environment:
      - COURSE_DIR=/app/files
      - COURSE_DB=/app/db/course.db
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./app/static:/usr/share/nginx/html
      - ./files:/usr/share/nginx/html/files
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
